Generic data reader
chhoumann/p3 pull request #46
Opened 2020-11-10 10:54 UTC by humleflue

Also moved the ICsvLineParser interface back to the DataReader

2020-11-10 12:14 UTC, Pattrigue commented on DataReader/ICsvLineParser.cs
> +        /// Should return a
Incomplete documentation

2020-11-10 12:16 UTC, Pattrigue requested changes
Please fix missing documentation

2020-11-10 12:46 UTC, Ivikhostrup approved these changes
Queen Elizabeth approves

2020-11-11 10:06 UTC, humleflue commented
Deprecated. We prefer using LINQ instead. See pr https://github.com/chhoumann/p3/pull/49

2020-11-11 10:06 UTC, closed without merging