Asset details
chhoumann/p3 pull request #47
Opened 2020-11-10 12:10 UTC by chhoumann

2020-11-11 10:35 UTC, humleflue commented on Server/Components/AssetTable/AssetTable.razor.cs
> +            string url = $"{NavigationManager.BaseUri}/AssetDetails/{asset.DbId}";
NavigationManager.BaseUri er umiddelbart tom. Er det intended?

2020-11-11 10:36 UTC, humleflue requested changes
Det ser godt ud, ud over den ene kommentar, som jeg har.

2020-11-11 10:36 UTC, humleflue commented on Server/Components/AssetTable/AssetTable.razor.cs
> +            string url = $"{NavigationManager.BaseUri}/AssetDetails/{asset.DbId}";
Det jeg mener er, at når jeg trykker details, så får jeg følgende URL: https://localhost:44353//AssetDetails/1

2020-11-11 10:36 UTC, humleflue commented on Server/Components/AssetTable/AssetTable.razor.cs
> +            string url = $"{NavigationManager.BaseUri}/AssetDetails/{asset.DbId}";
Jeg går ikke ud fra, at det er intended at have de to // ved siden af hinanden

2020-11-11 11:02 UTC, humleflue requested changes
En sidste ting, som jeg synes skal laves inden det merges er at der skal være en eller anden form for indikator på, at jeg kan klikke på detaljer-knappen, når jeg er på forsiden. Lige nu får jeg ingen indikator på at den er clickable. Dette synes jeg er lidt problematisk ud fra et DEB-perspektiv. Men hvis du synes at det er en task for sig, og at den er uoverskuelig, så synes jeg godt at vi kan merge.

2020-11-11 15:50 UTC, humleflue reviewed
Resten af rettelserne er bare min autoformatter.

2020-11-11 16:45 UTC, chhoumann commented
> En sidste ting, som jeg synes skal laves inden det merges er at der skal være en eller anden form for indikator på, at jeg kan klikke på detaljer-knappen, når jeg er på forsiden. Lige nu får jeg ingen indikator på at den er clickable. Dette synes jeg er lidt problematisk ud fra et DEB-perspektiv. Men hvis du synes at det er en task for sig, og at den er uoverskuelig, så synes jeg godt at vi kan merge.

Super underligt. Min indikerer fint. Blåt link med cursor = pointer. That's weird. Hvad ser du?

2020-11-12 08:44 UTC, humleflue commented
> > En sidste ting, som jeg synes skal laves inden det merges er at der skal være en eller anden form for indikator på, at jeg kan klikke på detaljer-knappen, når jeg er på forsiden. Lige nu får jeg ingen indikator på at den er clickable. Dette synes jeg er lidt problematisk ud fra et DEB-perspektiv. Men hvis du synes at det er en task for sig, og at den er uoverskuelig, så synes jeg godt at vi kan merge.
> 
> Super underligt. Min indikerer fint. Blåt link med cursor = pointer. That's weird. Hvad ser du?

På min PC ser det således ud. Der er heller ingen hover-effekt på "Send til bortskaffelse"
![image](https://user-images.githubusercontent.com/15886122/98916505-8ac41780-24cb-11eb-978f-a79989dafc54.png)

2020-11-12 10:09 UTC, chhoumann commented
> > > En sidste ting, som jeg synes skal laves inden det merges er at der skal være en eller anden form for indikator på, at jeg kan klikke på detaljer-knappen, når jeg er på forsiden. Lige nu får jeg ingen indikator på at den er clickable. Dette synes jeg er lidt problematisk ud fra et DEB-perspektiv. Men hvis du synes at det er en task for sig, og at den er uoverskuelig, så synes jeg godt at vi kan merge.
> > 
> > 
> > Super underligt. Min indikerer fint. Blåt link med cursor = pointer. That's weird. Hvad ser du?
> 
> På min PC ser det således ud. Der er heller ingen hover-effekt på "Send til bortskaffelse"
> ![image](https://user-images.githubusercontent.com/15886122/98916505-8ac41780-24cb-11eb-978f-a79989dafc54.png)

Fixed

2020-11-12 10:12 UTC, chhoumann commented
Merge conflicts resolved.

2020-11-12 11:25 UTC, humleflue approved these changes
LGTM!

2020-11-12 11:26 UTC, merged