Simple methods for moving an asset.
chhoumann/p3 pull request #52
Opened 2020-11-11 09:41 UTC by chhoumann

2020-11-11 10:11 UTC, humleflue reviewed
Jeg ved ikke om jeg synes at de her ændringer er nødvendige? Jeg synes det er unødvendigt at abstrahere over TransferAsset på den her måde.

2020-11-11 10:11 UTC, humleflue commented on NUnitTests/MoveAssetTests.cs
> +            IAsset asset = AssetController.MakeAsset(1, "M1", "Apple");
Har du prøvet at brug NSubstitute her. Det er ikke MakeAsset der er under test, så det synes jeg umiddelbart ville være bedre

2020-11-11 10:11 UTC, humleflue commented on NUnitTests/MoveAssetTests.cs
> +            IAssetHolder depot = new AssetHolder(AssetController.DepotLabel, null, null);
Igen: Se om du kan bruge NSubstitute

2020-11-11 16:00 UTC, humleflue commented on Models/AssetController.cs
> +        public static string DepotLabel { get; } = "Depot";
De her bør nok være AssetHolders i stedet?

2020-11-11 16:01 UTC, humleflue commented on Models/AssetController.cs
> +        public static string DepotLabel { get; } = "Depot";
`public static AssetHolder { get; } = new AssetHolder("Depot")` (Med et overload af AssetHolder constructoren)

2020-11-11 17:07 UTC, chhoumann commented on Models/AssetController.cs
> +        public static string DepotLabel { get; } = "Depot";
Enig!

2020-11-11 17:07 UTC, chhoumann commented on NUnitTests/MoveAssetTests.cs
> +            IAsset asset = AssetController.MakeAsset(1, "M1", "Apple");
Kan ikke, doesn't work

2020-11-11 17:07 UTC, chhoumann commented on NUnitTests/MoveAssetTests.cs
> +            IAssetHolder depot = new AssetHolder(AssetController.DepotLabel, null, null);
Kan ikke, doesn't work

2020-11-12 10:24 UTC, Pattrigue commented on .gitignore
> +/AssetManagement.v3.ncrunchsolution
Why ncrunchsolution?

2020-11-12 10:25 UTC, Pattrigue commented on Models/AssetController.cs
> +        public static readonly IAssetHolder Depot = new AssetHolder("Depot", null, null);
Public fields are illegal in C#. Use an auto-property or a getter property if they need to be accessible from outside. Otherwise, make them private.

2020-11-12 11:06 UTC, chhoumann commented on Models/AssetController.cs
> +        public static readonly IAssetHolder Depot = new AssetHolder("Depot", null, null);
Fixed

2020-11-12 11:14 UTC, humleflue reviewed
I like this 😁

2020-11-12 11:59 UTC, laurits-mumberg submitted a review, later dismissed
Nice, har intet der springer mig i øjnene. Kan godt lide at TransferTo er private

2020-11-12 13:27 UTC, Pattrigue requested changes

2020-11-12 13:27 UTC, Pattrigue commented on Models/Asset/Asset.cs
> +        }
Redundant constructor - its content should be moved to the other constructor so we only have one.

2020-11-12 13:27 UTC, Pattrigue commented on Models/Asset/Asset.cs
> +        private readonly Asset _asset;
"_asset" is against the project conventions, should be "asset".

2020-11-12 13:27 UTC, Pattrigue commented on Models/Asset/Asset.cs
> +        public void ToCage() => TransferTo(StaticAssetHolders.Cage);
Missing space for readability.

2020-11-12 13:27 UTC, Pattrigue commented on Models/Asset/Asset.cs
> +    public class AssetOwnershipManager
Should be sealed and should be in its own .cs file.

2020-11-12 13:27 UTC, Pattrigue commented on Models/Asset/IAsset.cs
> +        AssetOwnershipManager Transfer { get; }
IAsset should not depend on an AssetOwnershipManager, because then AssetData cannot implement IAsset.

2020-11-12 13:27 UTC, Pattrigue commented on Models/AssetHolder/StaticAssetHolders.cs
> +    public class StaticAssetHolders
Should be a static class.

2020-11-12 13:27 UTC, Pattrigue commented on NUnitTests/MoveAssetTests.cs
> +            IAsset asset = new Asset(1, "M1", "Apple");
Recommend keeping the Asset object reference instead of typecasting to IAsset. IAsset should only contain data (check pull request for branch GenericDBAccess).

2020-11-12 13:31 UTC, chhoumann commented on NUnitTests/MoveAssetTests.cs
> +                $"Expected {asset.CurrentAssetHolder}. But got {AssetController.Cage.Label}");
That's just a structural design. You don't actually need the comments.

2020-11-12 13:33 UTC, chhoumann commented on Models/Asset/Asset.cs
> +        }
Moved AssetRecord.Add to this constructor. This is the constructor we use for creating new assets -- any other field instantiation is a bonus.

2020-11-12 13:34 UTC, chhoumann commented on Models/Asset/Asset.cs
> +        private readonly Asset _asset;
Fixed

2020-11-12 13:34 UTC, chhoumann commented on Models/Asset/Asset.cs
> +        public void ToCage() => TransferTo(StaticAssetHolders.Cage);
Don't agree but fixed.

2020-11-12 13:35 UTC, chhoumann commented on Models/Asset/Asset.cs
> +    public class AssetOwnershipManager
Agreed. Fixed.

2020-11-12 13:43 UTC, chhoumann commented on Models/Asset/IAsset.cs
> +        AssetOwnershipManager Transfer { get; }
Don't agree; AssetData should not exist.

2020-11-12 13:44 UTC, chhoumann commented on Models/AssetHolder/StaticAssetHolders.cs
> +    public class StaticAssetHolders
True! Forgot. Fixed now.

2020-11-12 13:46 UTC, chhoumann commented on NUnitTests/MoveAssetTests.cs
> +            IAsset asset = new Asset(1, "M1", "Apple");
Agreed. Fixed.

2020-11-16 12:29 UTC, chhoumann commented
🙏🙏🙏🙏

2020-11-16 12:46 UTC, Ivikhostrup approved these changes
The queen approves.

2020-11-16 12:48 UTC, merged