Strategy pattern
chhoumann/p3 pull request #65
Opened 2020-11-18 13:22 UTC by Ivikhostrup

2020-11-18 14:39 UTC, Pattrigue commented on Core/DataLoadStrategy/ComputerDataReader.cs
> +    public class ComputerDataReader : IAssetLoadStrategy
Please make classes sealed unless they are designed to be extensible

2020-11-18 14:39 UTC, Pattrigue commented on Core/DataLoadStrategy/AssetLoadContext.cs
> +    public class AssetLoadContext
Please make classes sealed unless they are designed to be extensible

2020-11-18 14:40 UTC, Pattrigue commented on Core/DataLoadStrategy/ComputerDataReader.cs
> +        public object ReadAssetFromFile(string filePath, char separator)
Should be generic instead

2020-11-19 08:11 UTC, laurits-mumberg commented on Core/DataLoadStrategy/ComputerDataReader.cs
> +    public class ComputerDataReader : IAssetLoadStrategy
Now sealed

2020-11-19 08:11 UTC, laurits-mumberg commented on Core/DataLoadStrategy/AssetLoadContext.cs
> +    public class AssetLoadContext
Now sealed

2020-11-19 08:12 UTC, laurits-mumberg commented on Core/DataLoadStrategy/ComputerDataReader.cs
> +        public object ReadAssetFromFile(string filePath, char separator)
Made the function ReadAssetFromFile generic. Is this what you were thinking?

2020-11-19 10:48 UTC, humleflue requested changes
Generally it looks fine. My biggest issue is, that right now it looks like you're committing to file data a bit too early in the process. I might be wrong though.

Nice work! :)

2020-11-19 10:48 UTC, humleflue commented on Core/DataLoadStrategy/AssetLoadContext.cs
> +            T result = (T)AssetLoadStrategy.ReadAssetFromFile(filePath, separator);
Is this always going to be a file?

2020-11-19 10:48 UTC, humleflue commented on Core/DataLoadStrategy/ComputerDataReader.cs
> +        public object ReadAssetFromFile(string filePath, char separator)
Maybe a generic stream could be given to the method to be able to handle data in a more generic way (Something Thomas was talking about)

2020-11-19 10:48 UTC, humleflue commented on Core/DataLoadStrategy/IAssetLoadStrategy.cs
> +        object ReadAssetFromFile(string filePath, char separator);
Maybe a generic stream could be given to the method to be able to handle data in a more generic way (Something Thomas was talking about)

2020-11-23 09:28 UTC, laurits-mumberg commented
Changed up the LoadData function, so that it no longer simply calls the given function. Previously the AssetLoadContext felt more as an extra step for calling a function, rather than an implementation of a strategy pattern. It is now specialized for csv files, which makes the use of a strategy pattern much more obvious. (IN MY HUMBLE OPINION)

2020-11-23 10:52 UTC, Pattrigue approved these changes
LGTM!

2020-11-23 10:56 UTC, merged