Event based asset records
chhoumann/p3 pull request #66
Opened 2020-11-19 10:10 UTC by humleflue

2020-11-19 10:41 UTC, Ivikhostrup commented on DataAccessLibrary/DataModels/AssetRecordData.cs
>      public class AssetRecordData
Should probably a sealed class

2020-11-19 10:52 UTC, laurits-mumberg requested changes

2020-11-19 10:52 UTC, laurits-mumberg commented on Core/AssetRecordManager.cs
> +        public void UpdateAssetHistory()
Kan ikke helt forstå navnet på den her funktionen. Funktionen opdaterer vel ikke noget, eller tager jeg fejl? Ellers ser det hele rigtig fint ud

2020-11-19 10:53 UTC, Ivikhostrup commented on Core/AssetRecordManager.cs
> +        public void UpdateAssetHistory()
Ikke nødvendigvis den bedste navngivning for funktion
Possible name for function: WatchForAssetStatusChanged, StatusChangedWatcher.

2020-11-19 10:56 UTC, humleflue commented on DataAccessLibrary/DataModels/AssetRecordData.cs
>      public class AssetRecordData
No clue. We didn't make this. Maybe @Pattrigue knows?

2020-11-19 10:57 UTC, humleflue commented on DataAccessLibrary/DataModels/AssetRecordData.cs
>      public class AssetRecordData
I'm not sure if ECF is going to be happy about it

2020-11-23 11:40 UTC, laurits-mumberg approved these changes
Nice boys. LGTM!

2020-11-23 11:42 UTC, chhoumann approved these changes
OK

2020-11-23 11:44 UTC, merged